version: '3.4'

volumes:
  datafiles:
  photosCars:

services:
  procar:
    image: ${DOCKER_REGISTRY-}procar
    build:
      context: .
      dockerfile: ProCar/Dockerfile
    depends_on:
      - db
    restart: always
    volumes:
      - photosCars:/app/Data/imgs/
    environment:
      ConnectionStrings__DefaultConnection: "server=db;port=3306;user=newuser;database=mydb;password=password;"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5000"
    expose:
    - "5000"

  db:
    image: mysql:8.0.33
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb

  proxy:
    build:
      context: ./ProCar/nginx
      dockerfile: Dockerfile

    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    
    links:
      - procar
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - proxy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
